services:
  postgres:
    image: postgres:16-alpine
    container_name: hc-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: healthcare_analytics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../../data/ddl/00_extensions.sql:/docker-entrypoint-initdb.d/00_extensions.sql
      - ../../data/ddl/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ../../data/ddl/02_dimensions.sql:/docker-entrypoint-initdb.d/02_dimensions.sql
      - ../../data/ddl/03_facts.sql:/docker-entrypoint-initdb.d/03_facts.sql
      - ../../data/ddl/04_indexes.sql:/docker-entrypoint-initdb.d/04_indexes.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d healthcare_analytics"]
      interval: 5s
      timeout: 5s
      retries: 10

  cube:
    image: cubejs/cube:v1.2.0
    container_name: hc-cube
    ports:
      - "4000:4000"
    environment:
      CUBEJS_DEV_MODE: "true"
      CUBEJS_API_SECRET: healthcare_cube_secret_change_in_prod
      CUBEJS_DB_TYPE: postgres
      CUBEJS_DB_HOST: postgres
      CUBEJS_DB_PORT: 5432
      CUBEJS_DB_NAME: healthcare_analytics
      CUBEJS_DB_USER: postgres
      CUBEJS_DB_PASS: postgres
      CUBEJS_DB_SSL: "false"
      CUBEJS_SCHEMA_PATH: model
      CUBEJS_WEB_SOCKETS: "true"
    volumes:
      - ../../cube/model:/cube/conf/model
      - ../../cube/cube.js:/cube/conf/cube.js
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: hc-redis
    ports:
      - "6379:6379"

  neo4j:
    image: neo4j:5.26-community
    container_name: hc-neo4j
    environment:
      NEO4J_AUTH: neo4j/neo4jpassword
      NEO4J_PLUGINS: '["apoc"]'
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

volumes:
  postgres_data:
  neo4j_data:
